apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: gaiagpu-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --bind-address=127.0.0.1
    - --config=/etc/kubernetes/gaiagpu-scheduler-config.yaml
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --secure-port=10260
    image: k8s.gcr.io/kube-scheduler:v1.23.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10260
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: gaiagpu-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: scheduler-config
      readOnly: true
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
  nodeSelector:
    node-role.kubernetes.io/master: "" 
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: scheduler-config
    hostPath:
      path: /etc/kubernetes
  - hostPath:
      path: /etc/localtime
      type: ""
    name: localtime