apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: gaiagpu-scheduler
predicates:
  - name: PodFitsHostPorts
  - name: PodFitsResources
  - name: NoDiskConflict
  - name: MatchNodeSelector
  - name: HostName  
extenders:
- urlPrefix: http://127.0.0.1:32767/gaiagpu-scheduler
  filterVerb: predicates
  enableHTTPS: false
  nodeCacheCapable: true
  ignorable: false
hardPodAffinitySymmetricWeight: 10
alwaysCheckAllPredicates: false  
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf