apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: gaiagpu-admission
  namespace: kube-system
spec:
  containers:
    - image: 10.119.46.41:30003/library/gaiagpu-admission-main:1.0
      imagePullPolicy: Always
      name: gaiagpu-admission
      env:
        - name: LOG_LEVEL
          value: "5"
      ports:
        - containerPort: 32767
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  priority: 2000000000
  priorityClassName: system-cluster-critical
  nodeSelector:
    node-role.kubernetes.io/master: ""
